### ISSUE TITLE
Bot not responding to commands in designated Discord channel

### ISSUE THREAD

**Issue by light-fa11** [pyamsoft/mousewatch#9]
Description:
I am experiencing an issue with the Discord bot, which does not seem to respond to commands in the designated channel. I have verified that the information within .env is valid and confirmed that the Discord bot is online.

Steps to reproduce:
-    Type a command in the designated Discord channel (e.g., !mouse show 04/20/2023)
-    The bot does not respond to the command

Expected behavior:
The bot should respond to the command with the appropriate response.

Actual behavior:
The bot does not respond to any commands in the designated Discord channel.

Additional information:
-    The bot is online and connected to the Discord server.
-    The .env file contains the correct information for the bot.
-    Terminal output showing "Bot logged in:  true" and "Watch for messages"
-    Restarted the bot multiple times.
-    I have confirmed that the bot has the necessary permissions to read and send messages in the designated channel.

Please don't hesitate to let me know if there is any additional information I can provide to help resolve this issue. Thank you.

**Comment by pyamsoft** [comment]
Hi,


I assume these issues you are experiencing is with the .env file configured with the BOT_CHANNEL_ID


does the bot work if you dont use the BOT_CHANNEL_ID variable and thus allow the not to respond from any channel?


That's how I have the bot setup in my own Discord

**Comment by light-fa11** [comment]
The Discord bot was unable to send messages to a specified server channel due to the privilege intents not being enabled. To resolve the issue, the necessary intents must be enabled in the Discord developer portal. Specifically, the "Server Members Intent" and the "Presence Intent" should be enabled at a minimum.

Suggestion, have a feature to scout for a particular park so that users don't receive notifications for other parks being open.

**Comment by pyamsoft** [comment]
Thanks for that note, I'll add it and clean up the readme

I'll think about adding filter as a feature, but generally since an MK passholder can park hop, caring about which park was actually open never mattered to me. I'll see about adding some flag in to filter by park.
